services:
  app:
    image: nocobase/nocobase:latest
    container_name: ${CONTAINER_NAME_APP}
    networks:
      - nocobase
    depends_on:
      - postgres
    environment:
      - APP_KEY=${APP_KEY}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - NOCOBASE_PKG_USERNAME=${NOCOBASE_PKG_USERNAME}
      - NOCOBASE_PKG_PASSWORD=${NOCOBASE_PKG_PASSWORD}
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - '${APP_PORT}:80'
    # init: true
  
  postgres:
    image: postgres:16
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    command: postgres -c wal_level=logical
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase

networks:
  nocobase:
    driver: bridge
